import { DITest } from "@tsed/di";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

import { PackagesService } from "./PackagesService.js";

function createItemsServiceMock(initial: any[] = []) {
  const state = {
    rows: [...initial],
    lastId: 0
  };

  return {
    readByQuery: vi.fn(async (query?: any) => {
      // apply filters first
      if (query?.filter?.type?._eq !== undefined) {
        const found = state.rows.filter((r) => r.type === query.filter.type._eq);
        return query.limit === -1 ? found : found.slice(0, query.limit ?? 1);
      }
      if (query?.filter?.name?._eq !== undefined) {
        const found = state.rows.filter((r) => r.name === query.filter.name._eq);
        return found.slice(0, query.limit ?? 1);
      }
      // junction queries
      if (query?.filter?.packages_id && query?.filter?.maintainers_id) {
        const found = state.rows.filter(
          (r) => r.packages_id === query.filter.packages_id._eq && r.maintainers_id === query.filter.maintainers_id._eq
        );
        return found.slice(0, query.limit ?? 1);
      }
      if (!query || query.limit === -1) return state.rows;
      return [];
    }),
    readOne: vi.fn(async (id: any) => {
      return state.rows.find((r) => r.id === id) ?? null;
    }),
    updateOne: vi.fn(async (id: any, data: any) => {
      const idx = state.rows.findIndex((r) => r.id === id);
      if (idx > -1) {
        state.rows[idx] = { ...state.rows[idx], ...data };
      }
      return id;
    }),
    createOne: vi.fn(async (data: any) => {
      const id = data.id ?? `id_${++state.lastId}`;
      const row = { ...data, id };
      state.rows.push(row);
      return id;
    }),
    _state: state
  };
}

import { DirectusContextService } from "@tsed-cms/infra/directus/DirectusContextService.js";

async function createFixture(itemsMock: any, junctionMock?: any) {
  const directusContextService = {
    getItemsService: vi.fn(async (collection: string) => {
      if (collection === "packages") return itemsMock;
      if (collection === "packages_maintainers") return junctionMock ?? createItemsServiceMock();
      throw new Error("Unexpected collection: " + collection);
    })
  };

  const service = await DITest.invoke(PackagesService, [
    {
      token: DirectusContextService,
      use: directusContextService
    }
  ]);

  return { service, directusContextService };
}

describe("PackagesService", () => {
  beforeEach(() => DITest.create({ cache: false }));
  afterEach(() => DITest.reset());

  it("findByName returns the package when found", async () => {
    const items = createItemsServiceMock([{ id: "p1", name: "@tsed/common", type: "library", status: "published" }]);

    const { service } = await createFixture(items);

    const res = await service.findByName("@tsed/common");
    expect(res).toEqual({ id: "p1", name: "@tsed/common", type: "library", status: "published" });
    expect(items.readByQuery).toHaveBeenCalledWith({ filter: { name: { _eq: "@tsed/common" } }, limit: 1 });
  });

  it("findByName returns null when not found", async () => {
    const items = createItemsServiceMock([{ id: "p1", name: "foo", type: "lib" }]);

    const { service } = await createFixture(items);

    const res = await service.findByName("bar");
    expect(res).toBeNull();
  });

  it("upsertOne updates existing package", async () => {
    const items = createItemsServiceMock([{ id: "p1", name: "pkg", type: "lib", status: "published", stars: 0 }]);

    const { service } = await createFixture(items);

    const updated = await service.upsertOne({ name: "pkg", type: "lib", stars: 10 } as any);

    expect(items.updateOne).toHaveBeenCalledWith("p1", { name: "pkg", type: "lib", stars: 10 });
    expect(updated).toEqual({ id: "p1", name: "pkg", type: "lib", status: "published", stars: 10 });
  });

  it("upsertOne creates new package with published status by default", async () => {
    const items = createItemsServiceMock([]);

    const { service } = await createFixture(items);

    const created = await service.upsertOne({ name: "new", type: "lib" } as any);

    expect(items.createOne).toHaveBeenCalledWith({ name: "new", type: "lib", status: "published" });
    // id is generated by mock as id_1
    expect(created).toEqual({ id: "id_1", name: "new", type: "lib", status: "published" });
  });

  it("listByType returns all packages of a given type", async () => {
    const items = createItemsServiceMock([
      { id: "p1", name: "a", type: "lib" },
      { id: "p2", name: "b", type: "tool" },
      { id: "p3", name: "c", type: "lib" }
    ]);

    const { service } = await createFixture(items);

    const list = await service.listByType("lib" as any);

    expect(items.readByQuery).toHaveBeenCalledWith({ filter: { type: { _eq: "lib" } }, limit: -1 });
    expect(list).toEqual([
      { id: "p1", name: "a", type: "lib" },
      { id: "p3", name: "c", type: "lib" }
    ]);
  });

  it("updateMetadata updates and returns the package", async () => {
    const items = createItemsServiceMock([{ id: "p1", name: "a", type: "lib", description: null, stars: 0 }]);

    const { service } = await createFixture(items);

    const result = await service.updateMetadata("p1" as any, { description: "desc", stars: 5 });

    expect(items.updateOne).toHaveBeenCalledWith("p1", { description: "desc", stars: 5 });
    expect(result).toEqual({ id: "p1", name: "a", type: "lib", description: "desc", stars: 5 });
  });

  it("ensureMaintainersLinks creates missing links and counts ensured ones", async () => {
    const items = createItemsServiceMock([{ id: "p1", name: "a", type: "lib" }]);
    const junction = createItemsServiceMock([{ id: "j1", packages_id: "p1", maintainers_id: "m2" }]);

    const { service } = await createFixture(items, junction);

    const count = await service.ensureMaintainersLinks("p1" as any, ["m1", "m2", "m3"]);

    // created for m1 and m3, ensured for m2 => total 3
    expect(count).toBe(3);
    expect(junction.createOne).toHaveBeenCalledTimes(2);
    expect(junction.createOne).toHaveBeenNthCalledWith(1, { packages_id: "p1", maintainers_id: "m1" });
    expect(junction.createOne).toHaveBeenNthCalledWith(2, { packages_id: "p1", maintainers_id: "m3" });
  });
});
